config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  root to: 'static_pages#index'

  get "category_first" => "categories#category_first" #categoryの個別ページのルーティング
  get "category_second" => "categories#category_second" #categoryの個別ページのルーティング
  get "category_third" => "categories#category_third" #categoryの個別ページのルーティング
  get "category_fourth" => "categories#category_fourth" #categoryの個別ページのルーティング

  patch "decide_address" => "addresses#decide_address" #複数住所から１つを選んでアドレスを更新する場合。
  get "confirmation_address" => "addresses#confirmation_address"

  patch "reservation" => "reservations#new"

  patch "new_order" => "payjp#new"
  post "pay" => "payjp#pay" #pay.jpルーティング
  get "thank_you" => "payjp#thank_you"
  patch "payment_confirmation" => "payjp#index" #デフォルト住所変更の際のルーティング
  get "payment_confirmation" => "payjp#index" #住所新規登録の際のルーティング
  post "add_to_cart" => "products#add_to_cart"
  post "decrement_from_cart" =>"products#decrement_from_cart"
  post "empty_cart" => "products#empty_cart"
  post "delete_from_cart" => "products#delete_from_cart"
  get "current_cart" => "products#current_cart"
  get "interview_tanaka_noodle" => "static_pages#interview_tanaka_noodle"
  get "interview_souen_rush" => "static_pages#interview_souen_rush"
  get "interview_chiyo_seaweed" => "static_pages#interview_chiyo_seaweed"
  get "about_us" => "static_pages#about_us"
  post "shipping_fee" => "shippings#shipping_fee" #送料を計算する

  get "category_sake" => "categories#category_sake"
  get "category_grocery" => "categories#category_grocery"
  get "category_food" => "categories#category_food"
  get "category_craft" => "categories#category_craft"
  get "trade_law" => "terms#trade_law"
  get "privacy" => "terms#privacy"
  get "shipping_fee" => "terms#shipping_fee"
  get "terms_of_service" => "terms#terms_of_service"

  get "inquiry" => "inquiries#index"
  post "inquiry/confirm" => "inquiries#confirm"
  post "inquiry/thanks" => "inquiries#thanks"

  get "mypage" => "static_pages#mypage"
  get "mypage_order" => "static_pages#mypage_order"
  get "mypage_address" => "static_pages#mypage_address"

  namespace :admin do
    root to: "products#index"
    get "/manage-listing/:id/photos/" => "products#photos", as: "manage_listing_photos"
    post "/status_update" => "products#status_update"
    resources :orders
    resources :products do
      collection {get "search"}
    end
  end

  resource :user do
    resources :addresses
    resources :orders
    resources :reviews
  end

  resources :addresses do
  end

  resources :theme_tags do
      resource :thumbnail
  end

  resources :types do
      resource :thumbnail
  end

  resources :products, only: [:show] do
    member do
      get :option_value
    end
  end

  resources :prices, only: [:show] do
  end

  resources :reservations do
  end

  resources :photos, only: [:create, :destroy]

  get '*path', controller: 'application', action: 'render_404'
  get '*path', controller: 'application', action: 'render_500'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	before_filter :current_cart

	def index
		@new_products = Product.find([31,35,36,46])
		@popular_products_pc = Product.find([33,34,35,36,40,41,42,43,45])
		@popular_products_sp = Product.find([32,34,35,36])
	end

  def about_us
  end

  def mypage
  end

  def mypage_order
  	respond_to do |format|
	  	format.js {render layout: false}
  	end
  end

  def mypage_address
  	@current_addresses=current_user.addresses
  	respond_to do |format|
  		format.js {render layout: false}
  	end
  end

	def interview_tanaka_noodle
	end

	def interview_souen_rush
	end

	def interview_chiyo_seaweed
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_us.html.erb
<section class="About__Jojima">
	<div class="AboutUs">
		<div class="AboutUs__first">
			<p>
				福岡県南西部に位置する久留米市<br>筑後川をはさんで佐賀県との県境に位置するのが私たちの暮らす城島町です<br>季節とともに色を変える田畑と360度を囲む山々<br>そしてそのすべてを包みこむ広い空<br><br>
				城島町で生まれ育った人や物を一言で言い表すならば、まあそんな田舎者です<br>ときに、それは人を笑い者にする際に使われますが<br>私たちはそこに含まれる温和や素直または真面目であったり愚直という気質に<br>居心地の良さそして誇りを感じているわけです
			</p>
		</div>
		<div class="AboutUs__second">
			<p>
				<br>私たちの歴史、文化、そして暮らしには、この九州最大の河川とともにあります<br>いろんなものがこの川を上って九州に伝わって<br>あるものは文化となり<br>あるものは産業となり<br>あるものは伝統となりました<br><br>日本酒の原料もこの大河の恵み<br>堆積した粘土質の土は瓦となって人々の暮らしを支えてきました<br><br>川がそばにある暮らし<br>それは私たちにとっては当たり前の風景なんです
			</p>
		</div>

		<div class="AboutUs__third">
			<p>
				しかしかつては<br>一夜にして町を飲み込んでしまうほどの暴れ川でした<br>当時の人々はそれを「一夜川」と読んで<br>恐れ、戦い<br>そして共存してきました<br><br>楽しいときも　つらいときも<br>どんなに時代が移り変わろうとも<br>筑後川は私たちの生活の一部ということは<br>変わりません<br><br>ここで生まれ、育った私たちと<br>そんな私たちが作ったものを<br>味わってほしい　感じてほしいのです
			</p>
		</div>
		<div class="AboutUs__fourth">
			<p>
				ここには何もないから<br>だからこそ新しく何かが生まれる<br>その喜びをみんなで分かち合いたい<br>昨日までの城島を知って<br>今日の城島を感じて<br>そして明日の城島を一緒に作っていきたい<br>そんな思いを「あしたの城島」に込めました</div>
			</p>
		</div>
</section>

app/views/static_pages/index.html.erb
<%= stylesheet_link_tag "desktop/web/static_pages", :media => "all" %>
<%= stylesheet_link_tag "desktop/web/product_list", :media => "all" %>

<div id="jojima-top">
  <section>
    <div class="Intro">
    <ul id="menu2">
      <% if user_signed_in? %>
        <% if current_user.provider %>
        <%# facebookログインしているとき %>
          <ul class="logininfo">
            <li>
              <%= image_tag current_user.image, class: "img-circle profile-0" %>
              <%= link_to current_user.name, edit_user_registration_path %></p>
            </li>
          </ul>
        <% else %>
        <ul class="logininfo">
        <%#  通常ログインのとき %>
          <li>
            <%= cl_image_tag("review_avator_iboesa.png", class: "img-circle profile-0") %>
            <%= link_to current_user.name, edit_user_registration_path %>
          </li>
        </ul>
        <% end %>
        <ul class="accountinfo">
          <li><%= link_to '注文履歴', user_orders_path, class: "Menu__item"%></li>
          <% if current_user.orders.present? %>
          <li><%= link_to 'レビュー', user_reviews_path %></li>
          <% end %>
          <li><%= link_to "ログアウト", destroy_user_session_path, class: "Menu__item" %></li>
        </ul>
       </li>
      <% else %>
       <li>アカウント
         <ul>
           <li><%= link_to "アカウントを作成", new_user_registration_path, class: "Menu__item" %></li>
           <li><%= link_to "ログイン", new_user_session_path, class: "Menu__item" %></li>
         </ul>
       </li>
      <% end %>
      <li class="nav1"><%= link_to "トップ", root_path %></li>
      <li class="nav2"><%= link_to "城島町について", about_us_path %></li>
      <li class="nav3"><%= link_to "お問い合わせ", inquiry_path%></li>
      <li class="nav4"><%= link_to "出品者紹介", "#" %></li>
    </ul>
  </ul>

    <div class="Intro__main">
      <img class="Intro__main--logo">
        <%= image_tag '//res.cloudinary.com/dmfclza05/image/upload/v1498882875/top/logo.png',size:"140x70", alt: "logo image of sakeviva" %>
      </img>
    <% unless @cart.blank? %>
      <ul class="Intro__main--cart">
        <li>
          <%= link_to current_cart_path do %>
            <%= fa_icon("shopping-cart 2x")%>
          <% end %>
        </li>
        <li>(<%= link_to_unless_current "#{@cart.items.inject(0) {|sum, product| sum + product.quantity}}", current_cart_path %>)</li>
      </ul>
    <% end %>
    </div>
    <div class="Intro__sub">
      <div class="Category"></div>
        <ul class="Category__menu">
          <li class="Category__item ">
            <div class ="Category__photo">
            <%= link_to cl_image_tag("category/category_sake.jpg", height: 230, width: 400, :class => "pc", alt: "酒の写真"),category_sake_path %>
            <%= link_to cl_image_tag("category/category_sake.jpg", height: 90, width: 150, :class => "sp", alt: "酒の写真"),category_sake_path %>
            </div>
            <%= link_to category_sake_path do %>
              <div class="Category__text">城島町の日本酒</div>
            <% end %>
          </li>
          <li class="Category__item">
            <div class ="Category__photo">
            <%= link_to cl_image_tag("category/category_grocery.jpg", height: 230, width: 400, :class => "pc", alt: "雑貨の写真"),category_grocery_path %>
            <%= link_to cl_image_tag("category/category_grocery.jpg", height: 90, width: 150, :class => "sp", alt: "雑貨の写真"),category_grocery_path %>
            </div>
            <%= link_to category_grocery_path do %>
              <div class="Category__text">城島町の雑貨</div>
            <% end %>
          </li>
          <li class="Category__item">
            <div class ="Category__photo">
            <%= link_to cl_image_tag("category/category_food.jpg", height: 230, width: 400, :class => "pc", alt: "特産品の写真"),category_food_path %>
            <%= link_to cl_image_tag("category/category_food.jpg", height: 90, width: 150, :class => "sp", alt: "特産品の写真"),category_food_path %>
            </div>
            <%= link_to category_food_path do %>
              <div class="Category__text">城島町の食</div>
            <% end %>
          </li>
          <li class="Category__item">
            <div class="Category__photo">
            <%= link_to cl_image_tag("category/category_craft.jpg", height: 230, width: 400, :class => "pc", alt: "工芸品の写真"),category_craft_path %>
            <%= link_to cl_image_tag("category/category_craft.jpg", height: 90, width: 150, :class => "sp", alt: "工芸品の写真"),category_craft_path %>
            </div>
            <%= link_to category_craft_path do %>
              <div class="Category__text">城島町の工芸品</div>
            <% end %>
           </li>
          </ul>
       </div>
     </div>
    <p class="Intro__news">明日の城島、遂にリリースしました！城島町自慢の商品をお楽しみください。</p>
    </div>
  </div>
  </section>

  <section>
    <div class="NewArrival">
      <h2 class="NewArrival__head">新入荷</h2>
      <p class="NewArrival__text">新商品、季節にあった商品をご紹介します。</p>

      <div class="NewArrivalPC">
        <ul class="ProductList">
        <% @new_products.each do |item| %>
        <%= link_to product_path(item.id) do %>
          <%= render 'partial/product_list_pc', item: item %>
        <% end %>
        <% end %>
        </ul>
      </div>

      <div class="NewArrivalSP">
        <ul class="ProductList">
          <% @new_products.each do |item| %>
          <%= link_to product_path(item.id) do %>
            <%= render 'partial/product_list_sp', item: item %>
          <% end %>
          <% end %>
        </ul>
    </div>
    </div>
  </section>

  <section>
    <div class="Popular">
      <h2 class="Popular__head">注目の商品</h2>
      <p class="Popular__text">注目が集まっている商品です。いかがでしょうか？</p>

      <div class="PopularPC">
        <ul class="Popular__all_pc">
        <% @popular_products_pc.each do |popular_product| %>
          <li class="Popular__item">
            <div class="Popular__sub">
              <img class="Popular__sub--photo"><%= link_to image_tag(popular_product.image.url, height: 80, width: 68, alt: "商品写真"), product_path(popular_product.id) %>
              </img>
            </div>
             <div class="Popular__main">
               <div class="Popular__main--title"><%= link_to popular_product.name, product_path(popular_product.id) %></div>
               <div class="Popular__main--price"><%= number_to_currency(popular_product.options.first.value) %> (税込)</div>
             </div>
          </li>
         <% end %>
         </ul>
       </div>

      <div class="PopularSP">
        <ul class="ProductList">
          <% @popular_products_sp.each do |item| %>
          <%= link_to product_path(item.id) do %>
            <%= render 'partial/product_list_sp', item: item %>
          <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </section>

  <section>
    <div class="JojimaMap">
    <%= link_to cl_image_tag("top/aboutjojima.jpg", height: 300, :class => 'pc', alt:"城島町についての写真"), about_us_path %>
    <%= link_to cl_image_tag("top_mobile/aboutjojima_mobile.jpg", height: 200, :class => 'sp',alt:"城島町についての写真"), about_us_path %>
    </div>
  </section>

  <section>
      <h3 class="InterviewPC__head">作り手インタビュー</h2>
      <p class="InterviewPC__text">商品にかける情熱やこだわり、城島町のこれまでとこれからについて、生産者の想いを聞いてきました。</p>
    <div class="InterviewPC">

      <div class="InterviewPC__section">
        <div class="InterviewPC__item">
          <div class="InterviewPC__sub">
            <img class="InterviewPC__sub--photo"><%= link_to cl_image_tag("top/tanaka_noodle_top.jpg", height: 240 , width: 200, alt:'インタビュアーの写真'),interview_tanaka_noodle_path %></img>
          </div>
          <div class="InterviewPC__main">
            <div class="InterviewPC__main--id">#01</div>
            <div class="InterviewPC__main--companyname">田中製麺</div>
            <div class="InterviewPC__main--name">田中稔和</div>

            <div class="InterviewPC__main--btn"><%= link_to 'インタビューを読む', interview_tanaka_noodle_path %></div>
          </div>
        </div>

        <div class="InterviewPC__item">
          <div class="InterviewPC__sub">
            <img class="InterviewPC__sub--photo"><%= link_to cl_image_tag("top/shimosaka_pic.png", height: 240 , width: 200, alt:'インタビュアーの写真'), interview_souen_rush_path %></img>
          </div>
          <div class="InterviewPC__main">
            <div class="InterviewPC__main--id">#02</div>
            <div class="InterviewPC__main--companyname">創筵</div>
            <div class="InterviewPC__main--name">下坂美佳</div>
            <div class="InterviewPC__main--btn"><%= link_to 'インタビューを読む', interview_souen_rush_path %></div>
          </div>
        </div>

        <div class="InterviewPC__item">
          <div class="InterviewPC__sub">
            <img class="InterviewPC__sub--photo"><%= link_to cl_image_tag("top/chiyonori_pic.jpg", height: 240 , width: 200, alt:'インタビュアーの写真'), interview_chiyo_seaweed_path %></img>
          </div>
          <div class="InterviewPC__main">
            <div class="InterviewPC__main--id">#03</div>
            <div class="InterviewPC__main--companyname">千代海苔</div>
            <div class="InterviewPC__main--name">千代島賢</div>
            <div class="InterviewPC__main--btn"><%= link_to 'インタビューを読む', interview_chiyo_seaweed_path %></div>
          </div>
        </div>
      </div>
    </div>

    <div class="InterviewSP">
      <ul class="InterviewSP__photo">
        <li><%= link_to cl_image_tag("top_mobile/tanaka_pic_mobile.jpg", height: 150, :class => 'sp-image', alt: "商品写真"),interview_tanaka_noodle_path %></li>
        <li><%= link_to cl_image_tag("top_mobile/shimosaka_pic_mobile.jpg", height: 150, :class => 'sp-image', alt: "商品写真"),interview_souen_rush_path %></li>
        <li><%= link_to cl_image_tag("top_mobile/chiyoshima_pic_mobile.jpg", height: 150, :class => 'sp-image', alt: "商品写真"),interview_chiyo_seaweed_path %></li>
      </ul>
    </div>
  </section>
</div>

app/views/static_pages/index_smart_phone.html.erb
<div id= "main">

 <div class= "category">
	<p>商品一覧</p>
	<ul>
	 	<li>日本酒</li>
	 	<li>特産品</li>
	 	<li>伝統工芸品</li>
	 	<li>雑貨</li>
	</ul>
 </div>

 <div class= "introduction">
 	<p>作り手の紹介</p>
 	<ul>
 		<li>なんとか酒蔵</li>
 		<li>なんとか酒蔵</li>
 	</ul>
 </div>

 <div class= "notice">
 <p>お知らせ</p>
 </div>
 
</div>

app/views/static_pages/mypage.html.erb
<%= stylesheet_link_tag "desktop/web/static_pages", :media => "all" %>

<section class="MyPage">
	<div class="MyPage__menu">
    <ul class="MyPage__menu--list">
      <li><%= link_to "注文履歴", mypage_order_path, :remote => true %></li>
      <li><%= link_to "郵送先登録情報", mypage_address_path, :remote => true %><li>
    </ul>
	</div>
  <div class="MyPage__details">
  </div>
  <div class="MyPage__address">
  </div>

</section>

app/views/static_pages/mypage_address.js.erb
$(".MyPage__address").html("<%= escape_javascript(render partial: 'addresses/edit_address') %>");

app/views/static_pages/mypage_order.js.erb
$(".MyPage__details").html("<%= escape_javascript(render partial: 'orders/index') %>");