config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  root to: 'static_pages#index'

  get "category_first" => "categories#category_first" #categoryの個別ページのルーティング
  get "category_second" => "categories#category_second" #categoryの個別ページのルーティング
  get "category_third" => "categories#category_third" #categoryの個別ページのルーティング
  get "category_fourth" => "categories#category_fourth" #categoryの個別ページのルーティング

  patch "decide_address" => "addresses#decide_address" #複数住所から１つを選んでアドレスを更新する場合。
  get "confirmation_address" => "addresses#confirmation_address"

  patch "reservation" => "reservations#new"

  patch "new_order" => "payjp#new"
  post "pay" => "payjp#pay" #pay.jpルーティング
  get "thank_you" => "payjp#thank_you"
  patch "payment_confirmation" => "payjp#index" #デフォルト住所変更の際のルーティング
  get "payment_confirmation" => "payjp#index" #住所新規登録の際のルーティング
  post "add_to_cart" => "products#add_to_cart"
  post "decrement_from_cart" =>"products#decrement_from_cart"
  post "empty_cart" => "products#empty_cart"
  post "delete_from_cart" => "products#delete_from_cart"
  get "current_cart" => "products#current_cart"
  get "interview_tanaka_noodle" => "static_pages#interview_tanaka_noodle"
  get "interview_souen_rush" => "static_pages#interview_souen_rush"
  get "interview_chiyo_seaweed" => "static_pages#interview_chiyo_seaweed"
  get "about_us" => "static_pages#about_us"
  post "shipping_fee" => "shippings#shipping_fee" #送料を計算する

  get "category_sake" => "categories#category_sake"
  get "category_grocery" => "categories#category_grocery"
  get "category_food" => "categories#category_food"
  get "category_craft" => "categories#category_craft"
  get "trade_law" => "terms#trade_law"
  get "privacy" => "terms#privacy"
  get "shipping_fee" => "terms#shipping_fee"
  get "terms_of_service" => "terms#terms_of_service"

  get "inquiry" => "inquiries#index"
  post "inquiry/confirm" => "inquiries#confirm"
  post "inquiry/thanks" => "inquiries#thanks"

  get "mypage" => "static_pages#mypage"
  get "mypage_order" => "static_pages#mypage_order"
  get "mypage_address" => "static_pages#mypage_address"

  namespace :admin do
    root to: "products#index"
    get "/manage-listing/:id/photos/" => "products#photos", as: "manage_listing_photos"
    post "/status_update" => "products#status_update"
    resources :orders
    resources :products do
      collection {get "search"}
    end
  end

  resource :user do
    resources :addresses
    resources :orders
    resources :reviews
  end

  resources :addresses do
  end

  resources :theme_tags do
      resource :thumbnail
  end

  resources :types do
      resource :thumbnail
  end

  resources :products, only: [:show] do
    member do
      get :option_value
    end
  end

  resources :prices, only: [:show] do
  end

  resources :reservations do
  end

  resources :photos, only: [:create, :destroy]

  get '*path', controller: 'application', action: 'render_404'
  get '*path', controller: 'application', action: 'render_500'

end

app/models/product.rb
class Product < ActiveRecord::Base
	attr_accessor :image, :image_cache
	mount_uploader :image, ImageUploader #これはproductモデルから商品画像をあげる際に必要。
	has_many :images
	has_many :photos
	accepts_nested_attributes_for :images, allow_destroy: true

	#validates :value, numericality: { only_integer: true, greater_than: 0}
	#↑登録の際に"valueは数値にしてください"とエラーが出るので、一旦コメントアウトでworkする。
	validates :name,:description, presence: true

	belongs_to :category
	belongs_to :theme_tag
	belongs_to :type
	belongs_to :price
	belongs_to :shop
	belongs_to :brand
	has_many :items
	has_one :order, dependent: :destroy
	has_many :options, dependent: :destroy
	accepts_nested_attributes_for :options, allow_destroy: true
	has_many :users, through: :reviews

	enum type: { 純米酒: 1, 本醸造: 2, 吟醸: 3, 大吟醸: 4, 焼酎: 5, 特別純米: 8, 純米大吟醸: 9, 純米吟醸: 10, その他: 11 } #絞り込み用
	scope :get_by_type, ->(type) {where(type: type)}

	enum price: { "〜5000円": 1, "5000円〜10000円": 2, "10000円〜": 3 }
	scope :get_by_price, ->(price) {where(price: price)}

	enum brand: { "花の露": 1,"比翼鶴": 2,"有薫": 3,"旭菊": 4,"池亀": 5,"杜の蔵": 6,"城島の酒": 7,"萬年亀": 8,"筑紫の誉": 9,}
	scope :get_by_brand, ->(brand) {where(brand: brand)}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::Base

	def index
		@products=Product.all
	end

	def search
	end

	def show
		@product=Product.find(params[:id])
		@options=@product.options
		@images=@product.images.all
	end

	def new
		@product=Product.new
		@product.options.build
		@theme_tag=@product.theme_tag
		@category=@product.category
		@type=@product.type
		@image=@product.images.build #メインフォト
		#2.times { @product.images.build } #写真を3枚アップするためのリレーションbuild
	end

	def edit
		@product = Product.find(params[:id])
		@product.options.build
		@images=@product.images
		@product.images.build
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to [:admin, @product], notice: "商品を登録しました"
		else
			render "new"
		end
	end
#		if @product.save
#			redirect_to [:admin, @product], notice: "商品を登録しました"
#		else
#			render "new"
#		end

	def update
		@product = Product.find(params[:id])
		@product.update(product_params)
		redirect_to action: "show", notice: "情報を更新しました"
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to [:admin, @product], notice: "商品を削除しました"
	end

	def photos
		@photo = Photo.new
		@product = Product.find(params[:id])
	end

	def status_update
		@product = Product.find(params[:id])
		@product.toggle!(:status)
		redirect_to action: "index", notice: "商品ステータスを更新しました"
	end

	private
	def product_params
		params.require(:product).permit(:name, :description,:image, :image_cache, :theme_tag_id, :type_id, :shop_id, :price_id, :category_id, :brand_id, :info, :remove_image, options_attributes: [:id, :title, :product_id, :value, :_destroy ], images_attributes: [:id, :product_id, :image, :image_cache, :_destroy])
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_action :authenticate_user!, only:[:add_to_cart]
before_filter :current_cart

	attr_accessor :product

	def index
		@products = Product.all
	end

	def search
	end

	def show
		@product = Product.find(params[:id])
		@options = @product.options
		@images = @product.images.all
		@recommended_products = Product.where(category_id: @product.category_id).order("RANDOM()").where(status: true).limit(4)

		@reviews = Review.where(product_id: @product.id)
		if @reviews.blank?
			@avg_rating = 0
		else
			@avg_rating = @reviews.average(:score)
		end

	end

	def new
		@product = Product.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def create
	end

	def update
	end

	def destroy
	end

	def add_to_cart
		product = Product.find(params[:id])
		@cart = find_cart
		quantity = params[:quantity].to_i
		@options = product.options
		option = @options.find_by(id: params[:option_id])
		@cart.add_product(product,quantity,option)
		cookies.delete(:total_shipping_fee)
		redirect_to_current_cart("カートに商品を追加しました")
	end

	def empty_cart
		session[:cart] = nil
		cookies.delete(:total_shipping_fee)
		cookies.delete(:total_price)
		redirect_to_current_cart("カートは空にしました")
	end

	def decrement_from_cart
		product = Product.find(params[:id])
		@cart = find_cart
		@cart.decrement_product(product)
		redirect_to_current_cart("数量を１つ減らしました")
	end

	def delete_from_cart
		product = Product.find(params[:id])
		@cart = find_cart
		@cart.delete_product(product)
		cookies.delete(:total_shipping_fee)
		redirect_to_current_cart ("商品をカートから削除しました")
	end

	def current_cart
		@prefecture_id = flash[:prefecture_id]
	  #shipping controllerからprefectureを受け取って、更新後も選択できる状態にしておく。
		@total_shipping_fee = cookies[:total_shipping_fee].to_i
		#shipping controllerからtotal_shipping_feeを受け取って、更新後も選択できる状態にしておく。
    @cart = find_cart
	end

	def option_value
		render partial: 'option_value', locals: {option_id: params[:option_id]}
	end


	private

	def find_cart
		unless session[:cart]
			session[:cart] = Cart.new
		end
		session[:cart]
	end


	def redirect_to_current_cart(msg)
		flash[:notice] = msg
		redirect_to :action => "current_cart"
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<table class="attr">
	<tr>
		<th><%= form.label :name, "商品名" %></th>
		<td><%= form.text_field :name %></td>
	</tr>

	<tr>
		<th><%= form.label :value, "価格" %></th>
		<td><%= form.number_field :value %></td>
	</tr>

	<tr>
		<th><%= form.label :description, "商品説明" %></th>
		<td><%= form.text_field :description %></td>
	</tr>

</table>

app/views/products/_option_value.html.erb
<%= number_to_currency(Option.all.find_by(id: option_id).value) %> (税込)
<%= hidden_field_tag :option_id, option_id %>

app/views/products/current_cart.html.erb
<%= stylesheet_link_tag "desktop/web/products", :media => "all" %>

<section class="Cart">
  <div class="StepNav"><%= cl_image_tag("step_nav/step_two.jpg", height: 55, width: 550, :class => 'pc', alt: "残りステップの画像") %></div>
  <div class="StepNav"><%= cl_image_tag("step_nav/step_two.jpg", height: 35, :class => 'sp', alt: "残りステップの画像") %></div>
  <% unless @cart.items.empty? %>
    <p>カートの中身</p>
    <ul class="Cart__list">
      <li class="Cart__list--name">商品名</li>
      <li class="Cart__list--details">商品説明</li>
      <li class="Cart__list--price">価格</li>
      <li class="Cart__list--quantity">数量</li>
      <li class="Cart__list--unitprice">小計</li>
    </ul>

    <% for item in @cart.items %>

    <ul class="Cart__item">
      <li class="Cart__item--image">
      <%= image_tag(item.image.url, height: 120, width: 100, :class => 'pc',alt: "酒の写真") %>
      <%= image_tag(item.image.url, height: 150, width: 120, :class => 'sp',alt: "酒の写真") %>
      </li>
      <li class="Cart__item--name"><%= link_to "#{item.name}", item.product %></li>
      <li class="Cart__item--description"><%= item.description.truncate(100, separator: '。', :omission => "。....") %></li>
      <li class="Cart__item--price"><%= number_to_currency(item.price) %> (税込)</li>
      <li class="Cart__item--quantity">
        <div class="Cart__item--number">
          <%= item.quantity %>
        </div>
        <div class="Cart__item--updown ">
          <%= button_to :action => 'add_to_cart', :id => item.id, :method => :post ,:class => 'increment_button' do %>
          <i class="fa fa-chevron-up"></i>
          <% end %>
          <%= button_to :action => "decrement_from_cart", :id => item.id, :method => :post, :class => 'decrement_button' do %>
          <i class="fa fa-chevron-down"></i>
          <% end %>
        </div>
      </li>
      <li class="Cart__item--subtotal_price"><%= number_to_currency(item.subtotal_price) %> (税込)</li>
      <%= button_to "削除", :action => "delete_from_cart", :id => item.id, :method => :post %>
    </ul>
    <% end %>
  <% else %>
  <p>カートは空です。</p>
  <% end %>
</section>

<section class="CartAction">
  <div class="CartAction__emptycart"><%= button_to "カートを空にする", :action => "empty_cart" %></div>
  <div class="CartAction__continue"><%= link_to "買い物を続ける", root_path %></div>
</section>

<section class="CheckOut">
  <div class="CheckOut__shipping">
  <%= form_tag ({controller: :shippings, action: :shipping_fee, :method => :post}) do %>
    <p>送料を計算</p>
    <span style="font-size: 14px">送り先を選ぶ</span>
    <div class="CheckOut__shipping--select">
      <%= collection_select :prefecture, :prefecture_id, Prefecture.all, :id, :name, :selected => @prefecture_id %>
    </div>
    <% for item in @cart.items %>
      <%= hidden_field_tag ":shop_id[]", item.product.shop_id %>
    <% end %>
    <% unless @cart.items.empty? %>
      <div class="CheckOut__shipping--btn"><%= submit_tag "送料を計算" %></div>
    <% else %>
      <div class="CheckOut__shipping--nobtn">送料を計算</div>
    <% end %>
  <% end %>

  </div>
  <div class="CheckOut__calculation">
    <p>合計</p>
    <table>
      <tr>
        <td>小計</td>
        <td><%= number_to_currency(@cart.total_price) %></td>
      </tr>
      <tr>
        <td>送料</td>
        <td>
          <%= number_to_currency(@total_shipping_fee) %>
        </td>
      </tr>
      <tr>
        <td>合計</td>
        <td>
        <% if @total_shipping_fee.present? %>
        <% total_price = @cart.total_price + @total_shipping_fee %>
        <%= number_to_currency(total_price) %>
        <% end %>
        </td>
      </tr>
    </table>
    <% unless @total_shipping_fee == 0 || @cart.total_price == 0 %>
      <div class="CheckOut__calculation--btn">
        <%= link_to "レジへ進む", user_addresses_path(cookies[:total_price] = total_price) %>
      </div>
    <% else %>
      <div class="CheckOut__calculation--nobtn">レジへ進む</div>
    <% end %>
  </div>
</section>

app/views/products/edit.html.erb
<%= form_for @product do |form| %>
	<div class="product_form">
		<%= render "form", form:form %>
	</div>

	<div class="form_action">
		<%= form.submit %>
	</div>
<% end %>

app/views/products/new.html.erb
<%= stylesheet_link_tag "desktop/web/products", :media => "all" %>

<%= form_for @product do |form| %>
	<div class="product_form">
		<%= render "form", form: form %>
	</div>

	<div class="form_action">
		<%= form.submit %>
	</div>
<% end %>

app/views/products/show.html.erb
<%= stylesheet_link_tag "desktop/web/products", :media => "all" %>

<section>
	<% breadcrumb :product %>
	<div class="ItemDetails">
		<div class="ItemDetails__sub">
			<div class="ItemDetails__sub--mainphoto">
				<%= image_tag @product.image.url, height: 480, width: 360, :class => 'pc', alt: "商品の写真" %>
				<%= image_tag @product.image.url, :class => 'sp', alt: "商品の写真" %>
			</div>
			<ul class="ItemDetails__sub--smallphoto">
				<% if @images.exists? %>
					<% @images.each do |sub_image| %>
						<li><%= link_to image_tag(sub_image.image.url, height: 120, width: 100), sub_image.image.url, :'data-lightbox' => sub_image.id %></li>
					<% end %>
				<% end %>
			</ul>
		</div>
		<div class="ItemDetails__main">
			<h1><%= @product.name %></h1>
			<p><%= simple_format(@product.description) %></p>

			<% unless @product.info.nil? %>
				<%= simple_format(@product.info, :class => "ItemDetails__main--info") %></p>
			<% end %>

			<ul class="ItemDetails__review">
      <% if @avg_rating == 0 %>
				<li>☆☆☆☆☆</li>
				<li>レビューはまだありません</li>
      <% else %>
				<li><div class="review_rating" data-score=" <%= @avg_rating %>" ></div></li>
        <li><%= @reviews.count %>レビュー</li>
      <% end %>
			</ul>
			<%= form_tag('/add_to_cart', :method => :post) do %>
			<p class="ItemDetails__main--price">
				<%= render partial: 'option_value', locals: {option_id: @options.first.id} %></p>
			<p>サイズ</p>
			<div class="ItemDetails__main--option">
				<%= select :option, :option_id, @options.map{|t| [t.title, t.id]} %>
				<i class="fa fa-angle-down" aria-hidden="true"></i>
			</div>
			<div class="ItemDetails__main--quantity">
				<p>個数</p>
				<%= select_tag 'quantity', options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) %>
				<i class="fa fa-angle-down" aria-hidden="true"></i>
			</div>
				<%= hidden_field_tag :id, @product.id %>
				<%= hidden_field_tag :shop_id, @product.shop_id %>
			<div class="middle_btn"><%= submit_tag "カートに入れる" %></div>
			<% end %>
		</div>
	</div>
</section>

<% unless @reviews.blank? %>
<section class="ProductReviews">
  <div class="ProductReviews__title">
    <h2><%= @reviews.count %>件のレビュー</h2>
    <p class="review_rating" data-score=" <%= @avg_rating %>" ></p>
  </div>
    <% @reviews.each do |review| %>
    <div class="ProductReviews__list">
      <div class="ProductReviews__list--highlight">
        <% if review.user.provider == "facebook" %>
        <%= image_tag review.user.image, class: "img-circle profile-1" %>
        <% else %>
        <%= cl_image_tag("review_avator_iboesa.png", class: "img-circle profile-1") %>
        <% end %>
        <div>
          <p><%= review.user.name %></p>
          <p><%= review.title %></p>
        </div>
      </div>
      <p class="review_rating" data-score=" <%= review.score %>" ></p>
      <p class="review_comment"><%= review.comment %></p>
    </div>
    <% end %>
</section>
<% end %>

<section>
	<div class="RecommendedItems">
		<h3>こちらもおすすめ</h3>

		 <div class="NewArrivalPC">
        <ul class="ProductList">
        <% @recommended_products.each do |item| %>
        <%= link_to product_path(item.id) do %>
          <%= render 'partial/product_list_pc', item: item %>
        <% end %>
        <% end %>
        </ul>
      </div>

      <div class="NewArrivalSP">
        <ul class="ProductList">
          <% @recommended_products.each do |item| %>
          <%= link_to product_path(item.id) do %>
            <%= render 'partial/product_list_sp', item: item %>
          <% end %>
          <% end %>
        </ul>
      </div>
   </div>
</section>


<script>
  $('.review_rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets'
  });
</script>