config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  root to: 'static_pages#index'

  get "category_first" => "categories#category_first" #categoryの個別ページのルーティング
  get "category_second" => "categories#category_second" #categoryの個別ページのルーティング
  get "category_third" => "categories#category_third" #categoryの個別ページのルーティング
  get "category_fourth" => "categories#category_fourth" #categoryの個別ページのルーティング

  patch "decide_address" => "addresses#decide_address" #複数住所から１つを選んでアドレスを更新する場合。
  get "confirmation_address" => "addresses#confirmation_address"

  patch "reservation" => "reservations#new"

  patch "new_order" => "payjp#new"
  post "pay" => "payjp#pay" #pay.jpルーティング
  get "thank_you" => "payjp#thank_you"
  patch "payment_confirmation" => "payjp#index" #デフォルト住所変更の際のルーティング
  get "payment_confirmation" => "payjp#index" #住所新規登録の際のルーティング
  post "add_to_cart" => "products#add_to_cart"
  post "decrement_from_cart" =>"products#decrement_from_cart"
  post "empty_cart" => "products#empty_cart"
  post "delete_from_cart" => "products#delete_from_cart"
  get "current_cart" => "products#current_cart"
  get "interview_tanaka_noodle" => "static_pages#interview_tanaka_noodle"
  get "interview_souen_rush" => "static_pages#interview_souen_rush"
  get "interview_chiyo_seaweed" => "static_pages#interview_chiyo_seaweed"
  get "about_us" => "static_pages#about_us"
  post "shipping_fee" => "shippings#shipping_fee" #送料を計算する

  get "category_sake" => "categories#category_sake"
  get "category_grocery" => "categories#category_grocery"
  get "category_food" => "categories#category_food"
  get "category_craft" => "categories#category_craft"
  get "trade_law" => "terms#trade_law"
  get "privacy" => "terms#privacy"
  get "shipping_fee" => "terms#shipping_fee"
  get "terms_of_service" => "terms#terms_of_service"

  get "inquiry" => "inquiries#index"
  post "inquiry/confirm" => "inquiries#confirm"
  post "inquiry/thanks" => "inquiries#thanks"

  get "mypage" => "static_pages#mypage"
  get "mypage_order" => "static_pages#mypage_order"
  get "mypage_address" => "static_pages#mypage_address"

  namespace :admin do
    root to: "products#index"
    get "/manage-listing/:id/photos/" => "products#photos", as: "manage_listing_photos"
    post "/status_update" => "products#status_update"
    resources :orders
    resources :products do
      collection {get "search"}
    end
  end

  resource :user do
    resources :addresses
    resources :orders
    resources :reviews
  end

  resources :addresses do
  end

  resources :theme_tags do
      resource :thumbnail
  end

  resources :types do
      resource :thumbnail
  end

  resources :products, only: [:show] do
    member do
      get :option_value
    end
  end

  resources :prices, only: [:show] do
  end

  resources :reservations do
  end

  resources :photos, only: [:create, :destroy]

  get '*path', controller: 'application', action: 'render_404'
  get '*path', controller: 'application', action: 'render_500'

end

app/models/image.rb
class Image < ActiveRecord::Base
	#これはimageモデルから商品画像をあげる際に必要。
	mount_uploader :image, ImageUploader
	belongs_to :product
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::Base
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:product_id, :image)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to controller: 'admin/products', action: 'show', id: @image.product.id, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy(image_params)
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:product_id, :image, :remove_image)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= image_tag @image.image %>
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :image %>画像を更新<br>
    <%= f.file_field :image %><br>
    画像を削除する
    <%= f.check_box :remove_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>画像を編集</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.product_id %></td>
        <td><%= image.image %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @image.product_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @image.image %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>